# This file was generated by GoReleaser. DO NOT EDIT.
cask "considered" do
  version "0.1.11"

  on_macos do
    on_arm do
      sha256 "88aec21b138f7cbb57b07c3de03df1a3865a2b729524cb503fd9b74cfc533f43"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.11_darwin_arm64/considered", "considered"
      rename "considered_v0.1.11_darwin_arm64/considered-scc", "considered-scc"
    end
    on_intel do
      sha256 "82a1ddc658d1dc0600d15e3d09793cb4374640f979ba2018605f8055e3057289"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.11_darwin_amd64/considered", "considered"
      rename "considered_v0.1.11_darwin_amd64/considered-scc", "considered-scc"
    end
  end
  on_linux do
    on_arm do
      sha256 "064cc6a5df7b4ff709a099f0af7dfb5d64ca552350c1dee3e232100d12e99386"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.11_linux_arm64/considered", "considered"
      rename "considered_v0.1.11_linux_arm64/considered-scc", "considered-scc"
    end
    on_intel do
      sha256 "e6d28509424b9fc8c69e47b3f6251723ece422578a5f8ea570310d9009adc077"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.11_linux_amd64/considered", "considered"
      rename "considered_v0.1.11_linux_amd64/considered-scc", "considered-scc"
    end
  end

  name "considered"
  desc "Repository policy and decision documentation"
  homepage "https://considered.quitepicky.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "considered"
  binary "considered-scc"

  # No zap stanza required
end
