# This file was generated by GoReleaser. DO NOT EDIT.
cask "considered" do
  version "0.1.11"

  on_macos do
    on_arm do
      sha256 "c8cd47e127c44537edd075740f42a7ee154351033d47e66e586fa5f64ab579c8"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.11_darwin_arm64/considered", "considered"
      rename "considered_v0.1.11_darwin_arm64/considered-scc", "considered-scc"
    end
    on_intel do
      sha256 "405b54768a6f7c251ce77f84523ea6afcb7640b596f14a5617bd537cdfdc3019"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.11_darwin_amd64/considered", "considered"
      rename "considered_v0.1.11_darwin_amd64/considered-scc", "considered-scc"
    end
  end
  on_linux do
    on_arm do
      sha256 "ca2fa27559d503d920d919c15ce3a5996f5d836484491f812e7dac781c6d7fed"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.11_linux_arm64/considered", "considered"
      rename "considered_v0.1.11_linux_arm64/considered-scc", "considered-scc"
    end
    on_intel do
      sha256 "d205d8289bbeff931bb19995dbb0f553d78c88cbd4a68a85380704fd8404e37e"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.11_linux_amd64/considered", "considered"
      rename "considered_v0.1.11_linux_amd64/considered-scc", "considered-scc"
    end
  end

  name "considered"
  desc "Repository policy and decision documentation"
  homepage "https://considered.quitepicky.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "considered"
  binary "considered-scc"

  # No zap stanza required
end
