# This file was generated by GoReleaser. DO NOT EDIT.
cask "considered" do
  version "0.1.12"

  on_macos do
    on_arm do
      sha256 "ce4210544c4962d2eb369dc1e4bba280b3481165f342a0655ae46a64991020c3"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.12_darwin_arm64/considered", "considered"
      rename "considered_v0.1.12_darwin_arm64/considered-scc", "considered-scc"
    end
    on_intel do
      sha256 "7a95b44741f7b5c8c99a9a71d16437884bca934eff57e08bc5acab00ccfd5863"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.12_darwin_amd64/considered", "considered"
      rename "considered_v0.1.12_darwin_amd64/considered-scc", "considered-scc"
    end
  end
  on_linux do
    on_arm do
      sha256 "a5334f2dc160bd4e927cc760e8fe39a2a52e7c5451df7664c513bd415bdb7060"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.12_linux_arm64/considered", "considered"
      rename "considered_v0.1.12_linux_arm64/considered-scc", "considered-scc"
    end
    on_intel do
      sha256 "05a956497797f2e51c44d08441f54c7940564b8fc9d65eaf29ec03443c11d43e"
      url "https://github.com/quitepicky/considered/releases/download/v#{version}/considered_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/quitepicky/considered/"
      rename "considered_v0.1.12_linux_amd64/considered", "considered"
      rename "considered_v0.1.12_linux_amd64/considered-scc", "considered-scc"
    end
  end

  name "considered"
  desc "Repository policy and decision documentation"
  homepage "https://considered.quitepicky.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "considered"
  binary "considered-scc"

  # No zap stanza required
end
